# Site settings
title: Giuseppe Del Campo
description: Personal website of Giuseppe Del Campo (21 Years Old, Student, Front end Developer)
url: "giuseppetm.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Giuseppe Del Campo

user_description: "I am a 21 years old computer science student at the University of Milan, in Italy.
I dedicate most of my time to front-end web development, but I also love video editing, programming, 
computer building, work out, and I have a passion for cinematography and piano playing."

user_title: Front End Developer

email: gdeambo@yahoo.it

# Google-analytics
# google-analytics:
# id: ""

exclude: ['package.json', 'src' , 'node_modules']
